[general]
import = [
  "~/.config/alacritty/tokyonight.toml",
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "SauceCodePro Nerd Font"
size = 15

[env]
TERM = "xterm-256color"

[terminal]
shell.program = "tmux-sessionizer"
shell.args = [
  "maxocub",
]
