import = [
  "~/.config/alacritty/catppuccin.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "SauceCodePro Nerd Font"
size = 16

[env]
TERM = "xterm-256color"
