# Use neovim
export EDITOR=nvim

# venv activation
alias a="source .venv/bin/activate"

# lazygit
alias g="lazygit"
alias gg="lazygit"

# neovim
alias v="nvim"
alias vi="nvim"

# Load and unload environment variables depending on the current directory.
eval "$(direnv hook bash)"

# Activate Starship prompt
eval "$(starship init bash)"

# Add atuin bin directory to PATH
source "$HOME/.atuin/bin/env"

# Activate atuin
# shellcheck source=/home/maxocub/.bash-preexec.sh
[[ -f ~/.bash-preexec.sh ]] && source "$HOME/.bash-preexec.sh"
eval "$(atuin init bash)" || true
